// Code generated by "stringer -type Color"; DO NOT EDIT.

package rubiks_cube

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[White-0]
	_ = x[Yellow-1]
	_ = x[Orange-2]
	_ = x[Green-3]
	_ = x[Red-4]
	_ = x[Blue-5]
	_ = x[UnknownColor-255]
}

const (
	_Color_name_0 = "WhiteYellowOrangeGreenRedBlue"
	_Color_name_1 = "UnknownColor"
)

var (
	_Color_index_0 = [...]uint8{0, 5, 11, 17, 22, 25, 29}
)

func (i Color) String() string {
	switch {
	case i <= 5:
		return _Color_name_0[_Color_index_0[i]:_Color_index_0[i+1]]
	case i == 255:
		return _Color_name_1
	default:
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
