// Code generated by "stringer -type Facing,EdgeFacing,EdgePosition"; DO NOT EDIT.

package rubiks_cube

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FacingUpDown-0]
	_ = x[FacingFrontBack-1]
	_ = x[FacingRightLeft-2]
}

const _Facing_name = "FacingUpDownFacingFrontBackFacingRightLeft"

var _Facing_index = [...]uint8{0, 12, 27, 42}

func (i Facing) String() string {
	if i >= Facing(len(_Facing_index)-1) {
		return "Facing(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Facing_name[_Facing_index[i]:_Facing_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EdgeNormal-0]
	_ = x[EdgeOpposite-1]
}

const _EdgeFacing_name = "EdgeNormalEdgeOpposite"

var _EdgeFacing_index = [...]uint8{0, 10, 22}

func (i EdgeFacing) String() string {
	if i >= EdgeFacing(len(_EdgeFacing_index)-1) {
		return "EdgeFacing(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EdgeFacing_name[_EdgeFacing_index[i]:_EdgeFacing_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EdgeTopFront-0]
	_ = x[EdgeTopRight-1]
	_ = x[EdgeFrontRight-2]
}

const _EdgePosition_name = "EdgeTopFrontEdgeTopRightEdgeFrontRight"

var _EdgePosition_index = [...]uint8{0, 12, 24, 38}

func (i EdgePosition) String() string {
	if i >= EdgePosition(len(_EdgePosition_index)-1) {
		return "EdgePosition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EdgePosition_name[_EdgePosition_index[i]:_EdgePosition_index[i+1]]
}
