// Code generated by "stringer -type TurnOfCubelet"; DO NOT EDIT.

package rubiks_cube

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TurnOfUpDown-0]
	_ = x[TurnOfFrontBack-1]
	_ = x[TurnOfRightLeft-2]
}

const _TurnOfCubelet_name = "TurnOfUpDownTurnOfFrontBackTurnOfRightLeft"

var _TurnOfCubelet_index = [...]uint8{0, 12, 27, 42}

func (i TurnOfCubelet) String() string {
	if i >= TurnOfCubelet(len(_TurnOfCubelet_index)-1) {
		return "TurnOfCubelet(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TurnOfCubelet_name[_TurnOfCubelet_index[i]:_TurnOfCubelet_index[i+1]]
}
